id: P4B722EB2
initial_creation_type: ocr
source_metadata:
  volumes:
    a1c08d435093454a8386fc14e4205e1c:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: གནོད་པ་བ་ཆེན་པོས་ཀ་མ་ལ་ཤཱི་ལ་ལ་གནད་ཀྱི་གདམས་པ་བསྟན་པ།
      total_pages: 1953
      volume_number: 27
